[phases.setup]
nixPkgs = ["maven", "jdk17"]

[phases.build]
cmds = [
    "cd retro101-backend",
    "mvn clean package -DskipTests"
]

[start]
cmd = "java -jar retro101-backend/target/retro101-backend.jar"
