spring:
  config:
    activate:
      on-profile: production

server:
  port: ${PORT:8080}

allowed-origins: ${ALLOWED_ORIGINS}
frontend-url: ${FRONTEND_URL:https://retro101.vercel.app}

logging:
  level:
    com.retro101: INFO
