[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
    "cd retro101-frontend",
    "npm ci"
]

[phases.build]
cmds = [
    "cd retro101-frontend",
    "npm run build"
]

[start]
cmd = "cd retro101-frontend && npm run preview -- --port $PORT --host 0.0.0.0"
